// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr-UZLZcPZE4xNKzPuKBzvHJNh1fmhzE0',
    appId: '1:552752558366:web:f7935d0a57b2a18a32990f',
    messagingSenderId: '552752558366',
    projectId: 'bloom-tracker-6482c',
    authDomain: 'bloom-tracker-6482c.firebaseapp.com',
    storageBucket: 'bloom-tracker-6482c.firebasestorage.app',
    measurementId: 'G-V2BGSSRV66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7ait9CqIcvNmzEbUlc-1cKlE-a-Wb2Os',
    appId: '1:552752558366:android:3a1f164972d6817f32990f',
    messagingSenderId: '552752558366',
    projectId: 'bloom-tracker-6482c',
    storageBucket: 'bloom-tracker-6482c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-WNk7EKJM8-8N6eigK-03x28YBE5Xzmk',
    appId: '1:552752558366:ios:f90b51393999ec9d32990f',
    messagingSenderId: '552752558366',
    projectId: 'bloom-tracker-6482c',
    storageBucket: 'bloom-tracker-6482c.firebasestorage.app',
    iosBundleId: 'com.example.bloomMenstrualHealthWellnessTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-WNk7EKJM8-8N6eigK-03x28YBE5Xzmk',
    appId: '1:552752558366:ios:f90b51393999ec9d32990f',
    messagingSenderId: '552752558366',
    projectId: 'bloom-tracker-6482c',
    storageBucket: 'bloom-tracker-6482c.firebasestorage.app',
    iosBundleId: 'com.example.bloomMenstrualHealthWellnessTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr-UZLZcPZE4xNKzPuKBzvHJNh1fmhzE0',
    appId: '1:552752558366:web:ebee4a65ab64257032990f',
    messagingSenderId: '552752558366',
    projectId: 'bloom-tracker-6482c',
    authDomain: 'bloom-tracker-6482c.firebaseapp.com',
    storageBucket: 'bloom-tracker-6482c.firebasestorage.app',
    measurementId: 'G-FB8YLVG807',
  );
}
