// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0IyIg1NNJ8ouzT-0_gWmbXVNJKnOjLEc',
    appId: '1:806283459199:web:60a10c0da067d4b4e55d4a',
    messagingSenderId: '806283459199',
    projectId: 'bloom-d8864',
    authDomain: 'bloom-d8864.firebaseapp.com',
    storageBucket: 'bloom-d8864.firebasestorage.app',
    measurementId: 'G-608XYBXG75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWIJNiIMIOTf8vZ2FXBtFg6sUw7tzhjOY',
    appId: '1:806283459199:android:4773fafbfc984547e55d4a',
    messagingSenderId: '806283459199',
    projectId: 'bloom-d8864',
    storageBucket: 'bloom-d8864.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqfHan2KCAnLBC4HYNAPY1PyZfqUy8SQ8',
    appId: '1:806283459199:ios:c8a56615561b1126e55d4a',
    messagingSenderId: '806283459199',
    projectId: 'bloom-d8864',
    storageBucket: 'bloom-d8864.firebasestorage.app',
    iosBundleId: 'com.example.bloomMenstrualHealthWellnessTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqfHan2KCAnLBC4HYNAPY1PyZfqUy8SQ8',
    appId: '1:806283459199:ios:c8a56615561b1126e55d4a',
    messagingSenderId: '806283459199',
    projectId: 'bloom-d8864',
    storageBucket: 'bloom-d8864.firebasestorage.app',
    iosBundleId: 'com.example.bloomMenstrualHealthWellnessTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0IyIg1NNJ8ouzT-0_gWmbXVNJKnOjLEc',
    appId: '1:806283459199:web:4a8f41a9b5eef01ce55d4a',
    messagingSenderId: '806283459199',
    projectId: 'bloom-d8864',
    authDomain: 'bloom-d8864.firebaseapp.com',
    storageBucket: 'bloom-d8864.firebasestorage.app',
    measurementId: 'G-LMQPLFLCV6',
  );
}
